version: '3.8'

services:
  # Flask Application
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - mysql
      - postgresql
      - sqlserver
      - oracle
    volumes:
      - .:/app
    networks:
      - sqli-network

  # MySQL Database
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vulnerable_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database_setup.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sqli-network

  # PostgreSQL Database
  postgresql:
    image: postgres:13
    environment:
      POSTGRES_DB: vulnerable_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - sqli-network

  # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "Password123!"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - sqli-network

  # Oracle Database
  oracle:
    image: oracleinanutshell/oracle-xe-11g
    environment:
      ORACLE_PWD: password
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/u01/app/oracle
    networks:
      - sqli-network

volumes:
  mysql_data:
  postgresql_data:
  sqlserver_data:
  oracle_data:

networks:
  sqli-network:
    driver: bridge 