ALTER SESSION SET CONTAINER=FREEPDB1;

-- Crear tabla como SYS (el usuario con que corre el script)
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL,
    password VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (username, password, email) VALUES ('admin', 'admin123', 'admin@example.com');
INSERT INTO users (username, password, email) VALUES ('user1', 'password123', 'user1@example.com');
INSERT INTO users (username, password, email) VALUES ('user2', 'secret456', 'user2@example.com');
INSERT INTO users (username, password, email) VALUES ('test', 'test123', 'test@example.com');

CREATE TABLE products (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    price NUMBER(10,2) NOT NULL,
    description CLOB,
    category VARCHAR2(50)
);

INSERT INTO products (name, price, description, category) VALUES ('Laptop', 999.99, 'High performance laptop', 'Electronics');
INSERT INTO products (name, price, description, category) VALUES ('Mouse', 29.99, 'Wireless mouse', 'Electronics');
INSERT INTO products (name, price, description, category) VALUES ('Keyboard', 59.99, 'Mechanical keyboard', 'Electronics');
INSERT INTO products (name, price, description, category) VALUES ('Monitor', 299.99, '27 inch monitor', 'Electronics');

COMMIT;

-- Otorgar permisos a SYSTEM para acceder las tablas en SYS
GRANT SELECT, INSERT, UPDATE, DELETE ON users TO system;
GRANT SELECT, INSERT, UPDATE, DELETE ON products TO system;

-- Crear sinónimos en el esquema SYSTEM que apunten a SYS.USERS y SYS.PRODUCTS
BEGIN
  EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM system.users FOR sys.users';
  EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM system.products FOR sys.products';
END;
/

COMMIT;